# -*- coding: utf-8 -*-
"""Practice_list_dict.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juof1HMHnUUTigowokda9IaBT4JAV2Rx
"""

students = {
    1:{"name":"google","age":21},
    2:{"name":"aaa","age":22},
    3:{"name":"bbb","age":23},
    4:{"name":"cat","age":24},
    5:{"name":"dog","age":25},
}
for student_id, details in students.items():
    print(f"Student ID: {student_id}, Name: {details['name']},Age: {details['age']}")

import pandas as pd
data = [20,30,40,50,2,3,6,8,10,18,19,20,24,2,4,5,6]
No_of_studied = data[4:8]
print("No.of hours_studied",No_of_studied)
Age = data[9:13]
print("Student_age",Age)
screen_time = data[12:18]
print("screen_time",screen_time)
Data_Frame = pd.DataFrame(data)
print(Data_Frame)

def validate_password(password):
    if len(password) >=8:
    if any(char.isdigit() for char in password):
        return False
    if any(char.isupper() for char in password):
        return False